<a href="https://colab.research.google.com/github/JinFree/Thermo-and-Fluid-Engineering-Lab.1/blob/master/Thermo_and_Fluid_Engineering_Lab_1_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 기본
## Numpy의 기본 Array
* Array 선언 방법

In [0]:
import numpy as np
np.random.seed(4452)  # 재현성을 위한 랜덤 시드 설정

x1 = np.random.randint(10, size=6)  # 1차원 Array
x2 = np.random.randint(10, size=(3, 4))  # 2차원 Array
x3 = np.random.randint(10, size=(3, 4, 5))  # 3차원 Array

* Array의 기본 성질

In [2]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype: int64
itemsize: 8 bytes
nbytes: 480 bytes


## Array 
* Index

In [0]:
print(x1)

In [0]:
x1[0]

In [0]:
x1[4]

In [0]:
x1[-1]

In [0]:
x2

In [0]:
x2[0,0]

In [0]:
x2[2]

In [0]:
x2[2,0]

In [0]:
x2[2,-1]

In [0]:
x2[0,0]=12
x2

In [0]:
x2[0,0]=3.14159
x2

* Array Slice
 * x[시작:끝:간격]
 * 1차원인 경우 아래와 같음


In [14]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
x[:5]

array([0, 1, 2, 3, 4])

In [16]:
x[5:]

array([5, 6, 7, 8, 9])

In [17]:
x[4:7]

array([4, 5, 6])

In [18]:
x[::2]

array([0, 2, 4, 6, 8])

In [19]:
x[1::2]

array([1, 3, 5, 7, 9])

In [20]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [21]:
x[5::-2]

array([5, 3, 1])

* Array Slice
 * 다차원인 경우 아래와 같음

In [22]:
x2

array([[3, 7, 4, 8],
       [5, 9, 3, 7],
       [3, 5, 2, 7]])

In [23]:
x2[:2,:3]

array([[3, 7, 4],
       [5, 9, 3]])

In [24]:
x2[:3,::2]

array([[3, 4],
       [5, 3],
       [3, 2]])

In [25]:
x2[::-1,::-1]

array([[7, 2, 5, 3],
       [7, 3, 9, 5],
       [8, 4, 7, 3]])

* Array Slice
 * 특정 열 혹은 행 값 접근

In [26]:
x2[:,0]

array([3, 5, 3])

In [27]:
x2[0,:]

array([3, 7, 4, 8])

In [28]:
x2[0]

array([3, 7, 4, 8])

* Subarrays
 * 주소를 참조하는 Subarrays

In [29]:
x2

array([[3, 7, 4, 8],
       [5, 9, 3, 7],
       [3, 5, 2, 7]])

In [31]:
x2_sub = x2[:2, :2]
x2_sub

array([[3, 7],
       [5, 9]])

In [32]:
x2_sub[0,0] = 99
x2_sub

array([[99,  7],
       [ 5,  9]])

In [33]:
x2

array([[99,  7,  4,  8],
       [ 5,  9,  3,  7],
       [ 3,  5,  2,  7]])

* Subarrays
 * 데이터를 복사하는 Subarrays

In [34]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  7]
 [ 5  9]]


In [35]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  7]
 [ 5  9]]


In [36]:
print(x2)

[[99  7  4  8]
 [ 5  9  3  7]
 [ 3  5  2  7]]


* Array Reshape

In [37]:
arange = np.arange(1,10)
print(arange)
grid = arange.reshape((3, 3))
print(grid)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [39]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [40]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [41]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

* Array 나누거나 붙이기