<a href="https://colab.research.google.com/github/JinFree/Thermo-and-Fluid-Engineering-Lab.1/blob/master/Thermo_and_Fluid_Engineering_Lab_1_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Array 연산

## 반복문 속도

* Python의 기본 연산은 느리게 작동함
* C언어에서와 같이 반복문을 작성할 수는 있으나, 그 경우 연산 속도가 느림

In [0]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

* ```%timeit```을 통해 연산시간을 특정할 수 있음



In [0]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

## UFuncs

* Numpy에서는 Vectorized operation을 지원함

In [0]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [0]:
%timeit (1.0 / big_array)

100 loops, best of 3: 2.51 ms per loop


In [0]:
x1 = np.arange(5) 
x2 = np.arange(1, 6)
x3 = x1 / x2
print(x1)
print(x2)
print(x3)

[0 1 2 3 4]
[1 2 3 4 5]
[0.         0.5        0.66666667 0.75       0.8       ]


In [0]:
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

* Array 대수 연산

In [0]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [0]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [0]:
np.add(x, 2)

array([2, 3, 4, 5])

* **Operator Equivalent ufunc**
 * ''' + '''	np.add	Addition (e.g., 1 + 1 = 2)
 * ''' - '''	np.subtract	Subtraction (e.g., 3 - 2 = 1)
 * ''' - '''	np.negative	Unary negation (e.g., -2)
 * ''' * '''	np.multiply	Multiplication (e.g., 2 * 3 = 6)
 * ''' / '''	np.divide	Division (e.g., 3 / 2 = 1.5)
 * ''' // '''	np.floor_divide	Floor division (e.g., 3 // 2 = 1)
 * ''' ** '''	np.power	Exponentiation (e.g., 2 ** 3 = 8)
 * ''' % '''	np.mod	Modulus/remainder (e.g., 9 % 4 = 1)

* 절댓값

In [0]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [0]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [0]:
np.abs(x)

array([2, 1, 0, 1, 2])

* ufunc는 복소수도 다룰 수 있음

In [0]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

* 삼각함수

In [0]:
theta = np.linspace(0, np.pi, 3)

In [0]:
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [0]:
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


* 지수함수와 로그

In [0]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


In [0]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [0]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


# 기타 참고 자료
* https://jakevdp.github.io/PythonDataScienceHandbook/index.html